{% set name = "opentelemetry-instrumentation-asyncpg" %}
{% set version = "0.58b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_asyncpg-{{ version }}.tar.gz
  sha256: 8475db35d5f87b21e335c62e585fc554f23d898ae9adc07598181ad315d2c921

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.58b0
    - opentelemetry-semantic-conventions ==0.58b0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-asyncpg 
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-asyncpg 
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-asyncpg 
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-asyncpg 
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-asyncpg 
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-asyncpg 
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-asyncpg 
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0
    # - asyncpg >=0.12.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-asyncpg
  summary: OpenTelemetry instrumentation for AsyncPG
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
